drop table if exists votes;
drop table if exists dishes;
drop table if exists menus;
drop table if exists restaurants;
drop table if exists user_roles;
drop table if exists users;

create table restaurants
(
    ID      INTEGER generated by default as identity,
    primary key (id),
    NAME    VARCHAR(100) not null,
    ADDRESS VARCHAR(100) not null,
    constraint NAME_ADDRESS_UNIQUE_IDX unique (NAME, ADDRESS)
);

create table menus
(
    ID            INTEGER generated by default as identity,
    primary key (id),
    REGISTERED    DATE default NOW() not null,
    RESTAURANT_ID INTEGER            not null,
    constraint MENUS_UNIQUE_REGISTERED_IDX unique (REGISTERED, RESTAURANT_ID),
    constraint FK_RESTAURANT_ID foreign key (RESTAURANT_ID) references RESTAURANTS (ID)
);

create table dishes
(
    ID      INTEGER generated by default as identity,
    primary key (id),
    NAME    VARCHAR(100) not null,
    PRICE   BIGINT       not null,
    MENU_ID INTEGER      not null,
    constraint USERS_UNIQUE_EMAIL_IDX unique (NAME, MENU_ID),
    constraint FK_MENU_ID foreign key (MENU_ID) references MENUS (ID)
);

create table users
(
    ID         INTEGER generated by default as identity,
    primary key (id),
    NAME       VARCHAR(100)            not null,
    EMAIL      VARCHAR(100)            not null unique,
    PASSWORD   VARCHAR(100)            not null,
    REGISTERED TIMESTAMP default NOW() not null
);

create table user_roles
(
    USER_ID INTEGER not null,
    ROLE    VARCHAR(255),
    constraint FK_USER_ID foreign key (USER_ID) references USERS (ID)
);

create table votes
(
    id            INTEGER generated by default as identity,
    primary key (id),
    date          DATE default now() not null,
    restaurant_id integer            not null,
    user_id       integer            not null,
    constraint DATE_UNIQUE_USER_IDX unique (DATE, USER_ID),
    constraint FK_RESTAURANT_VOTE_ID foreign key (RESTAURANT_ID) references RESTAURANTS (ID),
    constraint FK_USER_VOTE_ID foreign key (USER_ID) references USERS (ID)
)